name: Build image and publish

on:
  push:
    tags:
     - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # TODO: Replace to github.repositoryUrl - ref https://docs.github.com/en/actions/learn-github-actions/contexts
          tags: murznn/website-php:latest,murznn/website-php:${{github.ref_name}}
